name: appenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dlib=19.24.2
  - face-recognition=1.3.0
  - opencv=4.5.5
  - numpy=1.24.4
  - pandas=1.5.3
  - pillow=10.3.0
  - streamlit=1.45.0
  - imageio
  - imageio-ffmpeg

